name: Build & Deploy

on:
  push:
    branches:
      - gh-pages
  pull_request:
    branches:
      - gh-pages

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Installing Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Installing NPM packages
        run: npm i

      - name: Building project
        run: CI=false && npm run build

      - name: Uploading production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./build

  deploy:
    name: Deploy GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    permissions:
      actions:	write
      checks:	write
      contents:	write
      deployments:	write
      id-token:	write
      issues:	write
      packages:	write
      pages:	write
      pull-requests:	write
      repository-projects:	write
      security-events:	write
      statuses:	write
    steps:
      - name: Downloading artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./build
      - name: Deploy GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
